-- inventory.sql
-- Closing stock table — separate from products, updated by DMS.
-- closing_stock = 0 means out of stock.
-- Update daily via DMS: UPDATE inventory SET closing_stock=N, last_updated=datetime('now') WHERE product_id='prod_XXX';

CREATE TABLE IF NOT EXISTS inventory (
    product_id      TEXT PRIMARY KEY,
    closing_stock   INTEGER NOT NULL DEFAULT 0,
    last_updated    TEXT NOT NULL,
    updated_by      TEXT DEFAULT 'manual',
    FOREIGN KEY (product_id) REFERENCES products(id)
);

-- Seeded from seed.sql — all 114 active SKUs, stock starts at 0.
-- Replace 0 with actual closing figures from your DMS.
INSERT OR IGNORE INTO inventory (product_id, closing_stock, last_updated, updated_by) VALUES
    ('prod_001', 0, datetime('now'), 'seed')  -- New Colour Plus Family Shampoo | 90 ml,
    ('prod_002', 0, datetime('now'), 'seed')  -- New Colour Plus Family Shampoo | 180 ml,
    ('prod_003', 0, datetime('now'), 'seed')  -- New Colour Plus Family Shampoo | 450 ml,
    ('prod_004', 0, datetime('now'), 'seed')  -- Nature Fresh Shampoo (AY) | 180ml,
    ('prod_005', 0, datetime('now'), 'seed')  -- Nature Fresh Shampoo (AY) | 500ml,
    ('prod_006', 0, datetime('now'), 'seed')  -- Nimson Herbal Shampoo | 500 ml,
    ('prod_007', 0, datetime('now'), 'seed')  -- Green Apple Shampoo | 500 ml,
    ('prod_008', 0, datetime('now'), 'seed')  -- Protine Shampoo | 500 ml,
    ('prod_009', 0, datetime('now'), 'seed')  -- Nimson Amla Hair Oil | 450 ml,
    ('prod_010', 0, datetime('now'), 'seed')  -- Nimson Amla Hair Oil | 180 ml,
    ('prod_011', 0, datetime('now'), 'seed')  -- Nimson Amla Hair Oil | 90 ml,
    ('prod_012', 0, datetime('now'), 'seed')  -- Nimson Coconut Jasmine Hair Oil | 450 ml,
    ('prod_013', 0, datetime('now'), 'seed')  -- Nimson Coconut Jasmine Hair Oil | 180 ml,
    ('prod_014', 0, datetime('now'), 'seed')  -- Nimson Coconut Jasmine Hair Oil | 90 ml,
    ('prod_015', 0, datetime('now'), 'seed')  -- Nimson Keshsilk Plus Hair Oil | 450 ml,
    ('prod_016', 0, datetime('now'), 'seed')  -- Nimson Keshsilk Plus Hair Oil | 180 ml,
    ('prod_017', 0, datetime('now'), 'seed')  -- Nimson Keshsilk Plus Hair Oil | 90 ml,
    ('prod_018', 0, datetime('now'), 'seed')  -- Nimson Keshsilk Plus Hair Oil | 50 ml,
    ('prod_019', 0, datetime('now'), 'seed')  -- Nimson Kesh Silk Oil | 120 ml,
    ('prod_020', 0, datetime('now'), 'seed')  -- Nimson Almond Hair Oil | 100ml,
    ('prod_021', 0, datetime('now'), 'seed')  -- Nimson Almond Hair Oil | 200 ml,
    ('prod_022', 0, datetime('now'), 'seed')  -- Nimson Almond Hair Oil | 500 ml,
    ('prod_023', 0, datetime('now'), 'seed')  -- Divyaratna Cool Cool Hair Oil | 90 ml,
    ('prod_024', 0, datetime('now'), 'seed')  -- Divyaratna Cool Cool Hair Oil | 180 ml,
    ('prod_025', 0, datetime('now'), 'seed')  -- Divyaratna Cool Cool Hair Oil | 450 ml,
    ('prod_026', 0, datetime('now'), 'seed')  -- Coconut Oil | 50 ml,
    ('prod_027', 0, datetime('now'), 'seed')  -- Coconut Oil | 90 ml,
    ('prod_028', 0, datetime('now'), 'seed')  -- Coconut Oil | 175 ml,
    ('prod_029', 0, datetime('now'), 'seed')  -- Coconut Oil | 500 ml,
    ('prod_030', 0, datetime('now'), 'seed')  -- Nimson Himaryan Hair Oil | 100 ml,
    ('prod_031', 0, datetime('now'), 'seed')  -- Nimson Himaryan Hair Oil | 200 ml,
    ('prod_032', 0, datetime('now'), 'seed')  -- Nimson Himaryan Hair Oil | 500 ml,
    ('prod_033', 0, datetime('now'), 'seed')  -- X-Ice Talcum Powder | 100 gm,
    ('prod_034', 0, datetime('now'), 'seed')  -- X-Ice Talcum Powder | 20 GM,
    ('prod_035', 0, datetime('now'), 'seed')  -- Nimson Silk Plus Talcum Powder | 100 gm,
    ('prod_036', 0, datetime('now'), 'seed')  -- Nimson Silk Plus Talcum Powder | 20 GM,
    ('prod_037', 0, datetime('now'), 'seed')  -- Nimson Silk Plus Talcum Powder B1G1 | 300 gm,
    ('prod_038', 0, datetime('now'), 'seed')  -- Nimson Boroneem Talcum Powder B1G1 | 300 gm,
    ('prod_039', 0, datetime('now'), 'seed')  -- Nimson Boroneem Talcum Powder | 150 gm,
    ('prod_040', 0, datetime('now'), 'seed')  -- Nimson Boroneem Talcum Powder | 100 gm,
    ('prod_041', 0, datetime('now'), 'seed')  -- Nimson Boroneem Talcum Powder | 50 gm,
    ('prod_042', 0, datetime('now'), 'seed')  -- Nimson Boroneem Talcum Powder | 20 GM,
    ('prod_043', 0, datetime('now'), 'seed')  -- Hair removing Cream (Tube)MIX | 60 gm,
    ('prod_044', 0, datetime('now'), 'seed')  -- Hair removing Cream (Tube) ROSE | 60 gm,
    ('prod_045', 0, datetime('now'), 'seed')  -- Hair removing Cream (Tube)MIX | 25 gm,
    ('prod_046', 0, datetime('now'), 'seed')  -- Hair removing Cream ROSE | 25 gm,
    ('prod_047', 0, datetime('now'), 'seed')  -- NEW Fruit Glow Bleach | 43 gm,
    ('prod_048', 0, datetime('now'), 'seed')  -- NEW Fruit Glow Bleach | 9 gm,
    ('prod_049', 0, datetime('now'), 'seed')  -- NEW Gold Bleach | 43 gm,
    ('prod_050', 0, datetime('now'), 'seed')  -- NEW Gold Bleach | 9 gm,
    ('prod_051', 0, datetime('now'), 'seed')  -- Stabary Lip Jelly | 10 ml,
    ('prod_052', 0, datetime('now'), 'seed')  -- Coffee Lip Jelly | 10 ml,
    ('prod_053', 0, datetime('now'), 'seed')  -- Nimson Lip Guard | 10 ml,
    ('prod_054', 0, datetime('now'), 'seed')  -- Nimson Lip Guard | 10 ml,
    ('prod_055', 0, datetime('now'), 'seed')  -- Happy Lips Strawberry Lip Balm | 5 ml,
    ('prod_056', 0, datetime('now'), 'seed')  -- Aloevera & Cucumber Hydra Moist.Cream (AY) | 15 ml,
    ('prod_057', 0, datetime('now'), 'seed')  -- Aloevera & Cucumber Hydra Moist.Cream (AY) | 50 gm,
    ('prod_058', 0, datetime('now'), 'seed')  -- Aloevera & Cucumber Hydra Moist.Cream (AY) | 100 gm,
    ('prod_059', 0, datetime('now'), 'seed')  -- Fruit Glow Cream | 15 ml,
    ('prod_060', 0, datetime('now'), 'seed')  -- Fruit Glow Cream | 50 gm,
    ('prod_061', 0, datetime('now'), 'seed')  -- Fruit Glow Cream | 100 gm,
    ('prod_062', 0, datetime('now'), 'seed')  -- Fruit Glow Cream | 200 gm,
    ('prod_063', 0, datetime('now'), 'seed')  -- Fruit Glow Cream | 400 gm,
    ('prod_064', 0, datetime('now'), 'seed')  -- Honey & Almond (ayurvedic) | 15 ml,
    ('prod_065', 0, datetime('now'), 'seed')  -- Honey & Almond (ayurvedic) | 50 gm,
    ('prod_066', 0, datetime('now'), 'seed')  -- Honey & Almond (ayurvedic) | 100 gm,
    ('prod_067', 0, datetime('now'), 'seed')  -- Fruitglow Hand & Body Lotion | 20 ml,
    ('prod_068', 0, datetime('now'), 'seed')  -- Fruitglow Hand & Body Lotion | 90 gm,
    ('prod_069', 0, datetime('now'), 'seed')  -- Fruitglow Hand & Body Lotion B1G1 | 180 gm,
    ('prod_070', 0, datetime('now'), 'seed')  -- Fruitglow Hand & Body Lotion B1G1 | 450 gm,
    ('prod_071', 0, datetime('now'), 'seed')  -- Oats & Olive Moisturising Body Lotion | 20 ml,
    ('prod_072', 0, datetime('now'), 'seed')  -- Oats & Olive Moisturising Body Lotion | 90 ml,
    ('prod_073', 0, datetime('now'), 'seed')  -- Oats & Olive Moisturising Body Lotion B1G1 | 180 GM,
    ('prod_074', 0, datetime('now'), 'seed')  -- Oats & Olive Moisturising Body Lotion B1G1 | 450 GM,
    ('prod_075', 0, datetime('now'), 'seed')  -- Nimson Ayurvedic Petroleum Jelly | 14 ml,
    ('prod_076', 0, datetime('now'), 'seed')  -- Nimson Ayurvedic Petroleum Jelly | 21 gm,
    ('prod_077', 0, datetime('now'), 'seed')  -- Nimson Ayurvedic Petroleum Jelly | 42 gm,
    ('prod_078', 0, datetime('now'), 'seed')  -- Nimson Ayurvedic Petroleum Jelly | 7 gm,
    ('prod_079', 0, datetime('now'), 'seed')  -- Nimson Boroneem Cream | 20 GM,
    ('prod_080', 0, datetime('now'), 'seed')  -- Olive Body Oil with Italian olives | 100ml,
    ('prod_081', 0, datetime('now'), 'seed')  -- Olive Body Oil with Italian olives | 200ml,
    ('prod_082', 0, datetime('now'), 'seed')  -- Olive Body Oil with Italian olives | 500ml,
    ('prod_083', 0, datetime('now'), 'seed')  -- Glycerin Solutions 3 in 1 Benefirs | 50ml,
    ('prod_084', 0, datetime('now'), 'seed')  -- Glycerin Solutions 3 in 1 Benefirs | 110ml,
    ('prod_085', 0, datetime('now'), 'seed')  -- Glycerin Solutions 3 in 1 Benefirs | 200ml,
    ('prod_086', 0, datetime('now'), 'seed')  -- Gulab Jal Premium Rose water | 50ml,
    ('prod_087', 0, datetime('now'), 'seed')  -- Gulab Jal Premium Rose water | 100ml,
    ('prod_088', 0, datetime('now'), 'seed')  -- Nature Fresh Brilliantine | 90 ml,
    ('prod_089', 0, datetime('now'), 'seed')  -- AdI cream 30gm | 25gm,
    ('prod_090', 0, datetime('now'), 'seed')  -- Vasojelly Mix | 50 ml,
    ('prod_091', 0, datetime('now'), 'seed')  -- Vasojelly Mix | 14 ml,
    ('prod_092', 0, datetime('now'), 'seed')  -- Nimson Vasojelly White Petrolium Jelly | 100ml,
    ('prod_093', 0, datetime('now'), 'seed')  -- Nimson Rosemary Hair Oil 150ml + 30ml shampoo | 150ml+30ml,
    ('prod_094', 0, datetime('now'), 'seed')  -- Nimson Rosemary Hair Shampoo | 250ml,
    ('prod_095', 0, datetime('now'), 'seed')  -- Nimson Rosemary Hair Spray | 110ml,
    ('prod_096', 0, datetime('now'), 'seed')  -- Nimson Kerala Ayurvedic Oil | 150ml,
    ('prod_097', 0, datetime('now'), 'seed')  -- Nimson Vasojelly Strawberry Crush Face, Hand & Body Cream | 400gm,
    ('prod_098', 0, datetime('now'), 'seed')  -- Nimson Vasojelly Soothing Cocoa Face, Hand & Body Cream | 400gm,
    ('prod_099', 0, datetime('now'), 'seed')  -- Nimson Vasojelly Fresh Aloe Face, Hand & Body Cream | 400gm,
    ('prod_100', 0, datetime('now'), 'seed')  -- Nimson Vasojelly Radiant Glow Face, Hand & Body Cream | 400gm,
    ('prod_101', 0, datetime('now'), 'seed')  -- Vasojelly Soft Moisturizing Cream | 14 ml,
    ('prod_102', 0, datetime('now'), 'seed')  -- Nimson Papaya D-Tan Face Wash | 60ML,
    ('prod_103', 0, datetime('now'), 'seed')  -- Nimson Apple Face Wash | 60ML,
    ('prod_104', 0, datetime('now'), 'seed')  -- Nimson Strawary Face Wash | 60ML,
    ('prod_105', 0, datetime('now'), 'seed')  -- Nimson Neem Tulsi Face Wash | 60ML,
    ('prod_106', 0, datetime('now'), 'seed')  -- Charcoal face wash | 60ML,
    ('prod_107', 0, datetime('now'), 'seed')  -- Ubtan face wash | 60ML,
    ('prod_108', 0, datetime('now'), 'seed')  -- Vitamin C face wash | 60ML,
    ('prod_109', 0, datetime('now'), 'seed')  -- Charcoal face wash | 100ML,
    ('prod_110', 0, datetime('now'), 'seed')  -- Ubtan face wash | 100ML,
    ('prod_111', 0, datetime('now'), 'seed')  -- Vitamin C face wash | 100ML,
    ('prod_112', 0, datetime('now'), 'seed')  -- Sunscreen SPF 30 PA++ tubes | 60ml,
    ('prod_113', 0, datetime('now'), 'seed')  -- Sunscreen SPF 30 PA++ 200 bottle with pump | 200ml,
    ('prod_114', 0, datetime('now'), 'seed')  -- Nimson Turmeric Cream | 30gm;